import React from "react";
import Header from "./header/Header";
import Footer from "./footer/Footer";

import Script from 'next/script';
import Head from 'next/head';

const Layout: React.FC = ({ children }) => {
    return (
        <>
            <Head>
                <title>Host Cloud</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />

                <link 
                    rel="stylesheet" 
                    href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
                />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
            </Head>

            <Header/>
            { children }
            <Footer/>

            <Script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" />
            <Script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" />
            <Script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" />
            <Script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" data-auto-replace-svg="nest"/>
        </>
    );
}

export default Layout;